    policies:
      - name: EmbeddingPolicy
        ## Neural Network architecture 
        rnn_size: 128
        ## training
        epochs: 3000
        batch_size: [8, 64]
        random_seed: 42
        attn_shift_range: 10
        ## embedding parameters
        embed_dim: 150
        mu_pos: 0.7
        mu_neg: -0.1
        use_max_sim_neg: true
        featurizer:
          - name: FullDialogueTrackerFeaturizer
            state_featurizer:
              - name: LabelTokenizerSingleStateFeaturizer
      - name: FallbackPolicy
        nlu_threshold: 0.4
        core_threshold: 0.3
        fallback_action_name: 'action_default_fallback'
      - name: FormPolicy
      