policies:
- name: EmbeddingPolicy
  ## Neural Network architecture 
  rnn_size: 128
  ## training
  epochs: 3000
  batch_size: [8, 64]
  random_seed: 42
  attn_shift_range: 10
  ## embedding parameters
  embed_dim: 150
  mu_pos: 0.7
  featurizer:
  - name: FullDialogueTrackerFeaturizer
    state_featurizer:
    - name: LabelTokenizerSingleStateFeaturizer
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.7
  core_threshold: 0.3
  deny_suggestion_intent_name: "out_of_scope"
- name: FormPolicy
      